package com.bank.bian.workforcedevelopment;

import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Info;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;

/**
 * BIAN Service Domain: Workforce Development
 *
 * Business Area:      Business Support
 * Business Domain:    Human Resources
 * Functional Pattern: Develop
 * Asset Type:         Workforce Plan
 * Control Record:     Workforce Plan Development Project
 *
 * Generated by the bian-platform service generator (Phase 1 — shallow build).
 * Replace the in-memory store with real persistence and domain logic in Phase 2.
 */
@SpringBootApplication
public class Application {

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }

    @Bean
    public OpenAPI openApi() {
        return new OpenAPI().info(new Info()
                .title("Workforce Development — BIAN Semantic API")
                .description("Service Domain 'Workforce Development' (Develop pattern) "
                        + "operating on the 'Workforce Plan Development Project' control record.")
                .version("0.1.0"));
    }
}
